### ISSUE TITLE
Remove basic block state usage in Scheduler tests

### ISSUE THREAD

**Issue by limemloh** [Concordium/concordium-node#609] opened 2022-11-14 10:10 UTC
Several tests for the scheduler use the basic block state, because it is in-memory and the purpose of the tests is independent of the block state implementation. These should use the persistent block state instead, either with a temporary file being created or ideally with some in-memory blobstore.

**Comment by abizjak** [comment] 2022-12-04 13:33
This is a duplicate of #625 (or rather 625 is a duplicate of this one). So closing.

**Closed by abizjak** 2022-12-04 13:33 UTC
Labels: [Type] Task
